# Generated by Django 5.2.11 on 2026-02-14 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_subtask_progress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworker',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_workers', to='app.project'),
        ),
    ]
