# Generated by Django 5.2.11 on 2026-02-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_projectmanager_supervisors_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectmanager',
            table='app_user',
        ),
    ]
