# Generated by GitHub Copilot on 2026-03-02

import django.db.models.deletion
from django.db import migrations, models


def backfill_created_by_from_project(apps, schema_editor):
    Supervisors = apps.get_model('app', 'Supervisors')
    Client = apps.get_model('app', 'Client')

    # Populate created_by based on the owning ProjectManager of the linked project.
    for supervisor in Supervisors.objects.select_related('project_id').filter(created_by__isnull=True):
        project = getattr(supervisor, 'project_id', None)
        pm_user_id = getattr(project, 'user_id', None) if project else None
        if pm_user_id:
            supervisor.created_by_id = pm_user_id
            supervisor.save(update_fields=['created_by'])

    for client in Client.objects.select_related('project_id').filter(created_by__isnull=True):
        project = getattr(client, 'project_id', None)
        pm_user_id = getattr(project, 'user_id', None) if project else None
        if pm_user_id:
            client.created_by_id = pm_user_id
            client.save(update_fields=['created_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_supervisors_user_id_user_alter_client_user_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE app_supervisors ADD COLUMN IF NOT EXISTS created_by_id integer NULL;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE app_client ADD COLUMN IF NOT EXISTS created_by_id integer NULL;"
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='supervisors',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_supervisors',
                        to='app.user',
                    ),
                ),
                migrations.AddField(
                    model_name='client',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_clients',
                        to='app.user',
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_created_by_from_project, migrations.RunPython.noop),
    ]
