# Generated by Django 5.2.9 on 2026-03-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_supervisors_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial Period'), ('active', 'Active Subscription'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_years',
            field=models.IntegerField(default=0, help_text='Number of years paid for'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_1day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_3days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_7days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_years', models.IntegerField(default=1)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='app.user')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionWarning',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('warning_type', models.CharField(choices=[('7_days', '7 Days Warning'), ('3_days', '3 Days Warning'), ('1_day', '1 Day Warning'), ('expired', 'Expired Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_logs', to='app.user')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
