# Generated by Django 5.2.12 on 2026-03-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_user_payment_date_user_subscription_end_date_and_more'),
        ('app', '0042_client_address_fields'),
    ]

    operations = [
    ]
