# Generated by Django 5.2.11 on 2026-03-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_merge_20260311_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='inventory_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Checked Out', 'Checked Out'), ('Returned', 'Returned'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Checked Out', 'Checked Out'), ('Returned', 'Returned')], default='Checked Out', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usages', to='app.supervisors')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='app.inventoryitem')),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
    ]
