# Generated by Django 5.2.11 on 2026-03-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_inventoryitem_inventoryusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryusage',
            name='return_date',
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usages', to='app.project'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='checked_out_by',
            field=models.ForeignKey(db_column='supervisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usages', to='app.supervisors'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='inventory_item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='app.inventoryitem'),
        ),
    ]
