# Generated by Django 5.2.11 on 2026-03-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_align_inventoryusage_with_postgres'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryusage',
            name='field_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usages', to='app.fieldworker'),
        ),
    ]
