# Generated by Django 5.2.11 on 2026-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_add_field_worker_to_inventory_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryusage',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
