# Generated by Django 5.2.11 on 2026-03-11 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_fix_expected_return_date_to_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='app.project'),
        ),
    ]
