# Generated by Django 5.2.11 on 2026-04-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_inventory_units_and_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Checked Out', 'Checked Out'), ('Returned', 'Returned'), ('Maintenance', 'Maintenance'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Checked Out', 'Checked Out'), ('Returned', 'Returned'), ('Maintenance', 'Maintenance'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Deactivated', 'Deactivated')], default='Active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('field_worker', 'project', 'attendance_date')},
        ),
    ]
