# Generated by Django 5.2.13 on 2026-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskfieldworker',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtaskfieldworker',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
