# Generated by Django 5.2.13 on 2026-04-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_subtaskfieldworker_shift_end_and_more'),
        ('app', '0056_subtaskphoto'),
    ]

    operations = [
    ]
