# Generated by Django 5.2.13 on 2026-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_inventoryitem_price_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworker',
            name='damages_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldworker',
            name='damages_deduction_per_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fieldworker',
            name='damages_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldworker',
            name='damages_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fieldworker',
            name='damages_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
