# Generated by Django 5.2.13 on 2026-04-22 21:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_fieldworker_damages_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryusage',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='app.phase'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='unit_price_at_use',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='phase',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='phase',
            name='used_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='PhaseMaterialPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_plans', to='app.inventoryitem')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plans', to='app.phase')),
            ],
            options={
                'ordering': ['phase_id', 'inventory_item_id'],
                'unique_together': {('phase', 'inventory_item')},
            },
        ),
    ]
