# Generated by Django 5.2.13 on 2026-04-22 23:06
#
# These columns already exist in the live database (they were added
# out-of-band before they were declared on the model). We only need to
# sync Django's model state — not re-create them in the DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_inventoryusage_phase_inventoryusage_quantity_used_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='inventoryitem',
                    name='item_type',
                    field=models.CharField(
                        choices=[
                            ('Material', 'Material'),
                            ('Tool', 'Tool'),
                            ('Machine', 'Machine'),
                        ],
                        default='Tool',
                        max_length=30,
                    ),
                ),
                migrations.AddField(
                    model_name='inventoryitem',
                    name='unit_of_measure',
                    field=models.CharField(default='pcs', max_length=30),
                ),
            ],
        ),
    ]
