# Generated by Django 5.2.13 on 2026-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_inventoryitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasematerialplan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phasematerialplan',
            name='leftover_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phasematerialplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
