# Generated by Django 5.2.13 on 2026-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_project_on_hold_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Deactivated', 'Deactivated')], default='Active', max_length=20),
        ),
    ]
