# Generated by Django 5.2.13 on 2026-04-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasematerialplan',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_plans', to='app.subtask'),
        ),
    ]
