# Generated by Django 5.2.13 on 2026-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_phasematerialplan_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasematerialplan',
            name='inventory_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
