# Generated by Django 5.0+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0068_phasematerialplan_inventory_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldworker",
            name="damages_pm_covers",
            field=models.BooleanField(default=False),
        ),
    ]
