# Generated by Django 5.2.13 on 2026-04-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_subtaskcompletionrevertrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_kind', models.CharField(choices=[('supervisor', 'Supervisor'), ('pm', 'Project Manager')], max_length=20)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='app.supervisors')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_kind', 'recipient_supervisor', '-created_at'], name='app_inappno_recipie_7205f1_idx'), models.Index(fields=['recipient_kind', 'recipient_user', '-created_at'], name='app_inappno_recipie_5d12ac_idx')],
            },
        ),
    ]
