# Generated by Django 5.2.13 on 2026-04-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_in_app_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inappnotification',
            name='app_inappno_recipie_7205f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='inappnotification',
            name='app_inappno_recipie_5d12ac_idx',
        ),
    ]
