# Generated by Django 5.2.11 on 2026-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_phasematerialplan_plans_per_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasematerialplan',
            options={'ordering': ['phase_id', 'inventory_item_id', 'subtask_id']},
        ),
        migrations.AddField(
            model_name='fieldworkerdamage',
            name='pm_covers_approval_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
    ]
